version: '3.5'

networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: zookeeper:latest
    networks:
      - app-tier
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka
    networks:
      - app-tier
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  cassandra:
      hostname: cassandra
      image: cassandra:latest
      networks:
      - app-tier
      ports:
        - "9042:9042"
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10
  consumer:
    image: spring-cloud-kafka-stream-consumer:latest
    networks:
      - app-tier
    environment:
       CASSANDRA_HOST: cassandra:9042
       CASSANDRA_USER:
       CASSANDRA_PW:
       KAFKA_BROKERS: kafka:9092
    ports:
      - '8082:8082'
    restart: always
    depends_on:
      - kafka
      - cassandra