spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        ACCOUNT:
          destination: ACCOUNT
          contentType: application/json
        CREDIT_HISTORY:
          destination: CREDIT_HISTORY
          contentType: application/json