spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        ACCOUNT:
          destination: ACCOUNT
          contentType: application/json
        CREDIT_HISTORY:
          destination: CREDIT_HISTORY
          contentType: application/json